# Pandas (–ß–∞—Å—Ç—å 3)

> üöÄ –í —ç—Ç–æ–π –ø—Ä–∞–∫—Ç–∏–∫–µ –Ω–∞–º –ø–æ–Ω–∞–¥–æ–±—è—Ç—Å—è: `numpy==1.21.2, pandas==1.3.3` 

> üöÄ –£—Å—Ç–∞–Ω–æ–≤–∏—Ç—å –≤—ã –∏—Ö –º–æ–∂–µ—Ç–µ —Å –ø–æ–º–æ—â—å—é –∫–æ–º–∞–Ω–¥—ã: `!pip install numpy==1.21.2 pandas==1.3.3`

## –°–æ–¥–µ—Ä–∂–∞–Ω–∏–µ

* [–°–æ—Ö—Ä–∞–Ω–µ–Ω–∏–µ / –∑–∞–≥—Ä—É–∑–∫–∞ –¥–∞–Ω–Ω—ã—Ö (—Ä–∞–±–æ—Ç–∞ —Å CSV)](#–°–æ—Ö—Ä–∞–Ω–µ–Ω–∏–µ-/-–∑–∞–≥—Ä—É–∑–∫–∞-–¥–∞–Ω–Ω—ã—Ö-—Ä–∞–±–æ—Ç–∞-—Å-CSV)
  * [–ó–∞–¥–∞–Ω–∏–µ - —á—É—Ç–æ–∫ —Å–∞–º–æ—Å—Ç–æ—è—Ç–µ–ª—å–Ω–æ–≥–æ —Ä–∞–∑–±–æ—Ä–∞](#–ó–∞–¥–∞–Ω–∏–µ---—á—É—Ç–æ–∫-—Å–∞–º–æ—Å—Ç–æ—è—Ç–µ–ª—å–Ω–æ–≥–æ-—Ä–∞–∑–±–æ—Ä–∞)
* [–ó–∞–¥–∞—á–∫–∏](#–ó–∞–¥–∞—á–∫–∏)

–í —ç—Ç–æ–º –Ω–æ—É—Ç–±—É–∫–µ:
- CSV —Ñ–∞–π–ª—ã
- –ö—Ç–æ –Ω–µ —Ä–∞–±–æ—Ç–∞–µ—Ç —Ç–æ—Ç –µ—Å—Ç: –∑–µ–º–ª—é –ø—Ä–∏ –≤—Å—Ç—Ä–µ—á–µ —Å —Ç—Ä—É–¥–Ω–æ—Å—Ç—è–º–∏. –ó–∞–¥–∞—á–∫–∏

In [1]:
import pandas as pd
import numpy as np

## –°–æ—Ö—Ä–∞–Ω–µ–Ω–∏–µ / –∑–∞–≥—Ä—É–∑–∫–∞ –¥–∞–Ω–Ω—ã—Ö (—Ä–∞–±–æ—Ç–∞ —Å CSV)

–û–¥–Ω–∏–º –∏–∑ –≤–∞–∂–Ω—ã—Ö –∏–Ω—Å—Ç—Ä—É–º–µ–Ω—Ç–æ–≤ –≤ —Ä–∞–±–æ—Ç–µ —Å —Ç–∞–±–ª–∏—Ü–∞–º–∏ —è–≤–ª—è–µ—Ç—Å—è –≤–æ–∑–º–æ–∂–Ω–æ—Å—Ç—å —Å–æ—Ö—Ä–∞–Ω–∏—Ç—å —Ä–µ–∑—É–ª—å—Ç–∞—Ç—ã —Ä–∞–±–æ—Ç—ã –≤ —Ñ–∞–π–ª –∏–ª–∏ –∑–∞–≥—Ä—É–∑–∏—Ç—å –¥–∞–Ω–Ω—ã–µ –∏–∑ —Ñ–∞–π–ª–∞. –ü–æ–ª—å–∑–æ–≤–∞—Ç—å—Å—è –º—ã –±—É–¥–µ–º —Ñ–æ—Ä–º–∞—Ç–æ–º CSV, –∫–æ—Ç–æ—Ä—ã–π —è–≤–ª—è–µ—Ç—Å—è —Ç–µ–∫—Å—Ç–æ–≤—ã–º —Ñ–æ—Ä–º–∞—Ç–æ–º –¥–ª—è —Ö—Ä–∞–Ω–µ–Ω–∏—è —Ç–∞–±–ª–∏—Ü—ã. –§–æ—Ä–º–∞—Ç –ø—Ä–µ–¥—Å—Ç–∞–≤–ª—è–µ—Ç —Å–æ–±–æ–π —Ç–µ–∫—Å—Ç–æ–≤—ã–µ —Å—Ç—Ä–æ–∫–∏, –∫–∞–∂–¥–∞—è –∫–æ–ª–æ–Ω–∫–∞ —Ä–∞–∑–¥–µ–ª—è–µ—Ç—Å—è —Ä–∞–∑–¥–µ–ª–∏—Ç–µ–ª–µ–º (–∑–∞–ø—è—Ç–∞—è, —Ç–æ—á–∫–∞ –∑–∞–ø—è—Ç–æ–π –∏ –¥—Ä.), –ø–æ—ç—Ç–æ–º—É –µ–≥–æ –ø—Ä–æ—Å—Ç–æ –ø–æ–Ω—è—Ç—å –∏ –æ–±—Ä–∞–±–∞—Ç—ã–≤–∞—Ç—å, —Ç–∞–∫ –∫–∞–∫ –Ω–µ —Ç—Ä–µ–±—É–µ—Ç—Å—è –Ω–∏–∫–∞–∫–æ–≥–æ —Å–ø–µ—Ü–∏–∞–ª—å–Ω–æ–≥–æ –ø—Ä–æ—Ç–æ–∫–æ–ª–∞ –¥–ª—è –ø–æ–Ω–∏–º–∞–Ω–∏—è.

–î–ª—è —Å–æ—Ö—Ä–∞–Ω–µ–Ω–∏—è –¥–∞–Ω–Ω—ã—Ö –∏–º–µ–µ—Ç—Å—è –º–µ—Ç–æ–¥ `DataFrame.to_csv()`:

In [2]:
import string

df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3'],
    index=list(string.ascii_uppercase)[:15]
)
df.head(3)

   x1  x2  x3
A   0   8   0
B   0   1   9
C   6   4   2

In [3]:
# –î–ª—è —Å–æ—Ö—Ä–∞–Ω–µ–Ω–∏—è –∑–∞–¥–∞–µ—Ç—Å—è –ø—É—Ç—å –¥–æ —Ñ–∞–π–ª–∞
df.to_csv('my_first_file.csv')

–ß—Ç–æ–±—ã —É–±–µ–¥–∏—Ç—å—Å—è –≤ —Ä–∞–±–æ—Ç–µ –º–µ—Ç–æ–¥–∞ –Ω–∞–π–¥–∏—Ç–µ —Ñ–∞–π–ª —Ä—è–¥–æ–º —Å –Ω–æ—É—Ç–±—É–∫–æ–º –∏ –æ—Ç–∫—Ä–æ–π—Ç–µ –µ–≥–æ —á–µ—Ä–µ–∑ —Ä–µ–¥–∞–∫—Ç–æ—Ä.

> –ü—Ä–∏ —Ä–∞–±–æ—Ç–µ –≤ Google Colab —Å–ª–µ–≤–∞ –µ—Å—Ç—å –≤–∫–ª–∞–¥–∫–∞, –∫–æ—Ç–æ—Ä–∞—è –ø–æ–∫–∞–∑—ã–≤–∞–µ—Ç —Ñ–∞–π–ª—ã –Ω–∞ —Å–µ—Ä–≤–µ—Ä–µ.

–ü—Ä–∏ –æ—Ç–∫—Ä—ã—Ç–∏–∏ –º–æ–∂–Ω–æ —É–≤–∏–¥–µ—Ç—å —á–µ—Ç—ã—Ä–µ –∫–æ–ª–æ–Ω–∫–∏:
- –ö–æ–ª–æ–Ω–∫–∞ –∏–Ω–¥–µ–∫—Å–∞;
- –¢—Ä–∏ –∫–æ–ª–æ–Ω–∫–∏ –∏–∑ –Ω–∞—à–∏—Ö –¥–∞–Ω–Ω—ã—Ö.

–¢–µ–ø–µ—Ä—å, –∫–æ–≥–¥–∞ –º—ã –∏–º–µ–µ–º —Ñ–∞–π–ª CSV –≤ —Å–∏—Å—Ç–µ–º–µ - –º–æ–∂–µ–º –∏—Å–ø—ã—Ç–∞—Ç—å —Ñ—É–Ω–∫—Ü–∏—é –∑–∞–≥—Ä—É–∑–∫–∏ `pd.read_csv()`:

In [4]:
df = pd.read_csv('my_first_file.csv')
df.head(3)

  Unnamed: 0  x1  x2  x3
0          A   0   8   0
1          B   0   1   9
2          C   6   4   2

–í–∏–¥–Ω–∞ –æ–¥–Ω–∞ —è–≤–Ω–∞—è –ø—Ä–æ–±–ª–µ–º–∞ - —É –Ω–∞—Å –ø–æ—è–≤–∏–ª–∞—Å—å –∫–æ–ª–æ–Ω–∫–∞, –∫–æ—Ç–æ—Ä–∞—è –¥–æ–ª–∂–Ω–∞ –±—ã—Ç—å –∏–Ω–¥–µ–∫—Å–æ–º, –Ω–æ –æ–Ω–∞ —Å—Ç–∞–ª–∞ –Ω–æ–≤–æ–π –∫–æ–ª–æ–Ω–∫–æ–π, –∞ –∏–Ω–¥–µ–∫—Å—ã —Å–æ–∑–¥–∞–ª–∏—Å—å –Ω–æ–≤—ã–µ. –î–ª—è —Ä–µ—à–µ–Ω–∏—è –ø—Ä–æ–±–ª–µ–º—ã –ø—Ä–∏ –∑–∞–≥—Ä—É–∑–∫–µ –Ω–µ–æ–±—Ö–æ–¥–∏–º–æ —è–≤–Ω–æ –∑–∞–¥–∞—Ç—å, –∫–∞–∫–∞—è –∫–æ–ª–æ–Ω–∫–∞ —Å—á–∏—Ç–∞–µ—Ç—Å—è –∏–Ω–¥–µ–∫—Å–æ–º:

In [5]:
df = pd.read_csv('my_first_file.csv', index_col=0)
df.head(3)

   x1  x2  x3
A   0   8   0
B   0   1   9
C   6   4   2

–¢–µ–ø–µ—Ä—å –≤—Å–µ –æ—Ç–ª–∏—á–Ω–æ –∏ –¥–∞–Ω–Ω—ã–µ –∑–∞–≥—Ä—É–∑–∏–ª–∏—Å—å —Ç–∞–∫, –∫–∞–∫ –æ–Ω–∏ –¥–æ–ª–∂–Ω—ã –±—ã—Ç—å.

### –ó–∞–¥–∞–Ω–∏–µ - —á—É—Ç–æ–∫ —Å–∞–º–æ—Å—Ç–æ—è—Ç–µ–ª—å–Ω–æ–≥–æ —Ä–∞–∑–±–æ—Ä–∞

–†–∞–∑–±–µ—Ä–∏—Ç–µ—Å—å –≤ –∞—Ä–≥—É–º–µ–Ω—Ç–∞—Ö `DataFrame.to_csv()` –∏ —Å–æ—Ö—Ä–∞–Ω–∏—Ç–µ –¥–∞–Ω–Ω—ã–µ –≤ —Ñ–∞–π–ª —Ç–∞–∫, —á—Ç–æ–±—ã –≤ —Ñ–∞–π–ª –∏–Ω–¥–µ–∫—Å –Ω–µ —Å–æ—Ö—Ä–∞–Ω—è–ª—Å—è.

In [6]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3'],
    index=list(string.ascii_uppercase)[:15]
)
df.head(3)

df.to_csv('no_index.csv',index=False)
# TODO - —Å–æ—Ö—Ä–∞–Ω–∏—Ç—å –≤ —Ñ–∞–π–ª no_index.csv –±–µ–∑ –∏–Ω–¥–µ–∫—Å–æ–≤
df

   x1  x2  x3
A   4   7   9
B   1   3   4
C   4   5   4
D   6   1   2
E   5   2   6
F   1   2   2
G   2   4   8
H   7   0   7
I   3   8   6
J   4   5   5
K   8   7   9
L   8   8   9
M   1   5   2
N   5   3   3
O   3   2   1

## –ó–∞–¥–∞—á–∫–∏

–°–æ–∑–¥–∞–π—Ç–µ —Ñ—Ä–µ–π–º —Å —á–µ—Ç—ã—Ä–µ–º—è –∫–æ–ª–æ–Ω–∫–∞–º–∏:
- –ö–æ–ª–æ–Ω–∫–∞ —Å –∏–º–µ–Ω–∞–º–∏ (—Ç–∏–ø - –æ–±—ä–µ–∫—Ç—ã);
- –ö–æ–ª–æ–Ω–∫–∞ —Å —Å—Ç–∞–∂–µ–º —Ä–∞–±–æ—Ç—ã (—Ç–∏–ø - –≤–µ—â–µ—Å—Ç–≤–µ–Ω–Ω—ã–π);
- –ö–æ–ª–æ–Ω–∫–∞ —Å –≤–æ–∑—Ä–∞—Å—Ç–æ–º (—Ç–∏–ø - —Ü–µ–ª–æ—á–∏—Å–ª–µ–Ω–Ω—ã–π);
- –ö–æ–ª–æ–Ω–∫–∞ —Å –Ω–∞–∑–≤–∞–Ω–∏–µ–º –ª—é–±–∏–º–æ–≥–æ —Ü–≤–µ—Ç–∞ (—Ç–∏–ø - –∫–∞—Ç–µ–≥–æ—Ä–∏–∞–ª—å–Ω—ã–π);

–ò–º–µ–Ω–∞ –∫–æ–ª–æ–Ω–æ–∫ –∏ –∑–Ω–∞—á–µ–Ω–∏—è –ª—é–±—ã–µ, –Ω–µ –º–µ–Ω–µ–µ —Ç—Ä–µ—Ö –∑–∞–ø–∏—Å–µ–π (—Å—Ç—Ä–æ–∫) –≤ —Ñ—Ä–µ–π–º–µ.

In [7]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(5, 4)), 
    columns=['name', 'years', 'age','f_color'],
    index=list(string.ascii_uppercase)[:5]
)
df['age'].astype(int)

name=['One','Two','Three','Foure','Five']
years=[4.3,1.7,3.7,2.0,3.3]
age=[22,41,50,36,29]
f_color = ['red','green','blue','purple','yellow']

df['name']=name
df['years']=years
df['age']=age
df['f_color']=f_color
df = df.astype({"f_color": 'category'})
df.info()
print(df)
# TODO - —Å–æ–∑–¥–∞–π—Ç–µ —Ñ—Ä–µ–π–º –∏ –Ω–∞—Å—Ç—Ä–æ–π—Ç–µ –ø—Ä–∞–≤–∏–ª—å–Ω—ã–µ —Ç–∏–ø—ã –∫–æ–ª–æ–Ω–æ–∫
#           DataFrame.info() –¥–æ–∂–µ–Ω –æ—Ç–æ–±—Ä–∞–∂–∞—Ç—å —É–∫–∞–∑–∞–Ω–Ω—ã–µ —Ç–∏–ø—ã

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, A to E
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     5 non-null      object
 1   years    5 non-null      float64
 2   age      5 non-null      int64
 3   f_color  5 non-null      category
dtypes: category(1), float64(1), int64(1), object(1)
memory usage: 377.0+ bytes
    name  years  age f_color
A    One    4.3   22     red
B    Two    1.7   41   green
C  Three    3.7   50    blue
D  Foure    2.0   36  purple
E   Five    3.3   29  yellow

–í—ã–±–µ—Ä–∏—Ç–µ —á–∏—Å–ª–∞ –≤ —Ä—è–¥—É `ds1`, –∫–æ—Ç–æ—Ä—ã—Ö –Ω–µ—Ç –≤ —Ä—è–¥—É `ds2`:

> –ü–æ—á–∏—Ç–∞–π—Ç–µ –∏ –ø—Ä–∏–º–µ–Ω–∏–µ –º–µ—Ç–æ–¥ `Series.isin()`

In [8]:
ds1 = pd.Series([1, 2, 3, 4, 5])
ds2 = pd.Series([4, 5, 6, 7, 8, 1, 9])

f=ds1.isin(ds2)
list(ds1[~f])
# TODO - –≤—ã–±–µ—Ä–∏—Ç–µ –∑–Ω–∞—á–µ–Ω–∏—è –≤ ds1, –∫–æ—Ç–æ—Ä—ã—Ö –Ω–µ—Ç –≤ ds2: 
# [2, 3]

[2, 3]

–û—Å—Ç–∞–≤—å—Ç–µ –≤ —Ä—è–¥—É –¥–≤–∞ –Ω–∞–∏–±–æ–ª–µ–µ —á–∞—Å—Ç—ã—Ö –∑–Ω–∞—á–µ–Ω–∏—è, –æ—Å—Ç–∞–ª—å–Ω—ã–µ –∑–∞–º–µ–Ω–∏—Ç–µ –∑–Ω–∞—á–µ–Ω–∏–µ–º '–î—Ä—É–≥–æ–µ':

<details>
<summary>–ü–æ–¥—Å–∫–∞–∑–∫–∞ 1</summary>

–î–ª—è –æ–ø—Ä–µ–¥–µ–ª–µ–Ω–∏—è –Ω–∞–∏–±–æ–ª–µ–µ —á–∞—Å—Ç—ã—Ö –∑–Ω–∞—á–µ–Ω–∏–π –≤–æ—Å–ø–æ–ª—å–∑—É–π—Ç–µ—Å—å –º–µ—Ç–æ–¥–æ–º `Series.value_counts()`
</details>

<details>
<summary>–ü–æ–¥—Å–∫–∞–∑–∫–∞ 2</summary>

–ß—Ç–æ–±—ã –ø–æ–ª—É—á–∏—Ç—å –Ω–∞–∏–±–æ–ª–µ–µ —á–∞—Å—Ç—ã–µ –∑–Ω–∞—á–µ–Ω–∏—è –º–æ–∂–Ω–æ –≤–æ—Å–ø–æ–ª—å–∑–æ–≤–∞—Ç—å—Å—è —Ä–µ–∑—É–ª—å—Ç–∞—Ç–æ–º `Series.value_counts()` - –∞—Ç—Ä–∏–±—É—Ç–æ–º `Series.index`
</details>

<details>
<summary>–ü–æ–¥—Å–∫–∞–∑–∫–∞ 3</summary>

–ü–æ–ª—É—á–∏–≤ –Ω–∞–∏–±–æ–ª–µ–µ —á–∞—Å—Ç—ã–µ –∑–Ω–∞—á–µ–Ω–∏—è, –º–æ–∂–Ω–æ –∏–Ω–¥–µ–∫—Å–∏—Ä–æ–≤–∞—Ç—å –¥—Ä—É–≥–∏–µ —á–µ—Ä–µ–∑ –º–∞—Å–∫—É –º–µ—Ç–æ–¥–∞ `Series.isin()`
</details>

In [9]:
ds = pd.Series([2, 2, 2, 4, 4, 4, 3, 1, 1, 1, 1, 4])

f=ds.value_counts()
filter=~ds.isin(f.index[0:2])

for i in ds[filter]:
  ds.replace(i,'–î—Ä—É–≥–æ–µ', inplace=True)

print(list(ds))
# TODO - –æ–ø—Ä–µ–¥–µ–ª–∏—Ç–µ –¥–≤–∞ –Ω–∞–∏–±–æ–ª–µ–µ —á–∞—Å—Ç—ã—Ö –∑–Ω–∞—á–µ–Ω–∏—è –≤ —Ä—è–¥—É (1, 4),
#           –æ—Å—Ç–∞–ª—å–Ω—ã–µ –∑–∞–º–µ–Ω–∏—Ç–µ –∑–Ω–∞—á–µ–Ω–∏–µ–º '–î—Ä—É–≥–æ–µ'
# ['–î—Ä—É–≥–æ–µ', '–î—Ä—É–≥–æ–µ', '–î—Ä—É–≥–æ–µ', 4, 4, 4, '–î—Ä—É–≥–æ–µ', 1, 1, 1, 1, 4]

['–î—Ä—É–≥–æ–µ', '–î—Ä—É–≥–æ–µ', '–î—Ä—É–≥–æ–µ', 4, 4, 4, '–î—Ä—É–≥–æ–µ', 1, 1, 1, 1, 4]

–°–¥–µ–ª–∞–π—Ç–µ –∫–∞–∂–¥—É—é –ø–µ—Ä–≤—É—é –±—É–∫–≤—É –≤ —Å–ª–æ–≤–∞—Ö —Ä—è–¥–∞ –∑–∞–≥–ª–∞–≤–Ω–æ–π:

In [10]:
ds = pd.Series(['how', 'to', 'use', 'pandas?'])
def my_func(x):
  str(x)
  return x.title()
k = ds.apply(my_func)
print(k)

# TODO - —Å–¥–µ–ª–∞–π—Ç–µ –∫–∞–∂–¥—É—é –ø–µ—Ä–≤—É—é –±—É–∫–≤—É –∑–∞–≥–ª–∞–≤–Ω–æ–π —Å –ø–æ–º–æ—â—å—é Series.apply()

0        How
1         To
2        Use
3    Pandas?
dtype: object

–í—ã–±–µ—Ä–∏—Ç–µ –∑–∞–ø–∏—Å–∏ —Å –º–∞–∫—Å–∏–º–∞–ª—å–Ω—ã–º –∑–Ω–∞—á–µ–Ω–∏–µ–º –ø–æ –∫–æ–ª–æ–Ω–∫–µ `x1`:

In [11]:
df = pd.DataFrame(
    np.random.randint(0, 4, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
print(df)
max=df.aggregate(['max'], axis='rows')
x1_max=max['x1']
mask = (df['x1'] == int(x1_max))
df[mask]
# TODO - –≤—ã–±–µ—Ä–∏—Ç–µ —Ç–µ –∑–∞–ø–∏—Å–∏, –∫–æ—Ç–æ—Ä—ã–µ –∏–º–µ—é—Ç x1 —Ä–∞–≤–Ω—ã–π 
#           –º–∞–∫—Å–∏–º–∞–ª—å–Ω–æ–º—É –∑–Ω–∞—á–µ–Ω–∏—é –≤ –∫–æ–ª–æ–Ω–∫–µ x1

    x1  x2  x3
0    2   0   0
1    1   1   0
2    2   2   2
3    0   3   1
4    1   2   3
5    3   0   0
6    1   3   3
7    3   1   3
8    2   3   0
9    3   0   2
10   0   2   3
11   2   2   1
12   0   0   0
13   1   3   3
14   0   1   0

   x1  x2  x3
5   3   0   0
7   3   1   3
9   3   0   2

–í—ã–≤–µ–¥–∏—Ç–µ –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –ø—Ä–æ–ø—É—Å–∫–æ–≤ –≤ –∫–∞–∂–¥–æ–π –∫–æ–ª–æ–Ω–∫–µ –¥–∞–Ω–Ω—ã—Ö:

In [12]:
df = pd.read_csv('https://raw.githubusercontent.com/AleksDevEdu/ml_edu/master/datasets/Cars93_miss.csv')
df.isna().sum()
# TODO - –æ—Ç–æ–±—Ä–∞–∑–∏—Ç–µ –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –ø—Ä–æ–ø—É—Å–∫–æ–≤ –≤ –¥–∞–Ω–Ω—ã—Ö –ø–æ –∫–∞–∂–¥–æ–π –∫–æ–ª–æ–Ω–∫–µ

Manufacturer           4
Model                  1
Type                   3
Min.Price              7
Price                  2
Max.Price              5
MPG.city               9
MPG.highway            2
AirBags                6
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev.per.mile           6
Man.trans.avail        5
Fuel.tank.capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn.circle            5
Rear.seat.room         4
Luggage.room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64

–ó–∞–º–µ–Ω–∏—Ç–µ –ø—Ä–æ–ø—É—â–µ–Ω–Ω—ã–µ –∑–Ω–∞—á–µ–Ω–∏—è –≤ –∫–æ–ª–æ–Ω–∫–µ `Min.Price` —Å—Ä–µ–¥–Ω–∏–º –∑–Ω–∞—á–µ–Ω–∏—è–º –ø–æ —ç—Ç–æ–π –∫–æ–ª–æ–Ω–∫–µ:

In [13]:
df = pd.read_csv('https://raw.githubusercontent.com/AleksDevEdu/ml_edu/master/datasets/Cars93_miss.csv')


mean=df.aggregate(['mean'], axis='rows')
p_mean=mean['Min.Price']
df['Min.Price'].fillna(int(p_mean), inplace=True)
print(df)

pr=df.filter(items=['Min.Price'], axis='columns').isna()
print(pr.value_counts())

# TODO - –∑–∞–ø–æ–ª–Ω–∏—Ç–µ NaN –≤ –∫–æ–ª–æ–Ω–∫–µ Min.Price —Å—Ä–µ–¥–Ω–∏–º –∑–Ω–∞—á–µ–Ω–∏–µ–º –ø–æ —ç—Ç–æ–π –∫–æ–ª–æ–Ω–∫–µ
# NOTE - –ø–æ—Å–ª–µ –∑–∞–ø–æ–ª–Ω–µ–Ω–∏—è —É–±–µ–¥–∏—Ç–µ—Å—å, —á—Ç–æ –≤ —ç—Ç–æ–π –∫–æ–ª–æ–Ω–∫–µ –Ω–µ—Ç –ø—Ä–æ–ø—É—â–µ–Ω–Ω—ã—Ö

   Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small       12.9   15.9       18.8      25.0
1           NaN   Legend  Midsize       29.2   33.9       38.7      18.0
2          Audi       90  Compact       25.9   29.1       32.3      20.0
3          Audi      100  Midsize       17.0   37.7       44.6      19.0
4           BMW     535i  Midsize       17.0   30.0        NaN      22.0
..          ...      ...      ...        ...    ...        ...       ...
88   Volkswagen  Eurovan      Van       16.6   19.7       22.7      17.0
89   Volkswagen   Passat  Compact       17.6   20.0       22.4      21.0
90   Volkswagen  Corrado   Sporty       22.9   23.3       23.7      18.0
91        Volvo      240  Compact       21.8   22.7       23.5      21.0
92          NaN      850  Midsize       24.8   26.7       28.5      20.0

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                None      Front  ...        5.0   177.0
1          25.0  Driver & Passenger      Front  ...        5.0   195.0
2          26.0         Driver only      Front  ...        5.0   180.0
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0
4          30.0                 NaN       Rear  ...        4.0   186.0
..          ...                 ...        ...  ...        ...     ...
88         21.0                None      Front  ...        7.0   187.0
89         30.0                None      Front  ...        5.0   180.0
90         25.0                None      Front  ...        4.0   159.0
91         28.0         Driver only       Rear  ...        5.0   190.0
92         28.0  Driver & Passenger      Front  ...        5.0   184.0

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0
1       115.0   71.0         38.0           30.0          15.0  3560.0
2       102.0   67.0         37.0           28.0          14.0  3375.0
3       106.0    NaN         37.0           31.0          17.0  3405.0
4       109.0   69.0         39.0           27.0          13.0  3640.0
..        ...    ...          ...            ...           ...     ...
88      115.0   72.0         38.0           34.0           NaN  3960.0
89      103.0   67.0         35.0           31.5          14.0  2985.0
90       97.0   66.0         36.0           26.0          15.0  2810.0
91      104.0   67.0         37.0           29.5          14.0  2985.0
92      105.0   69.0         38.0           30.0          15.0  3245.0

     Origin                Make
0   non-USA       Acura Integra
1   non-USA        Acura Legend
2   non-USA             Audi 90
3   non-USA            Audi 100
4   non-USA            BMW 535i
..      ...                 ...
88      NaN  Volkswagen Eurovan
89  non-USA   Volkswagen Passat
90  non-USA  Volkswagen Corrado
91  non-USA           Volvo 240
92  non-USA           Volvo 850

[93 rows x 27 columns]
Min.Price
False        93
dtype: int64

–û—Ç—Å–æ—Ä—Ç–∏—Ä—É–π—Ç–µ –∏ –≤—ã–≤–µ–¥–∏—Ç–µ —Ñ—Ä–µ–π–º —Å –∫–æ–ª–æ–Ω–∫–∞–º–∏ –≤ –∞–ª—Ñ–∞–≤–∏—Ç–Ω–æ–º –ø–æ—Ä—è–¥–∫–µ:

In [14]:
df = pd.DataFrame(np.random.randint(0, 10, size=(5, 6)), columns=list('fbecda'))
col=list('fbecda')
col_s=sorted(col, reverse=True)
df.filter(items=col_s, axis='columns')

# TODO - –ø–æ–ª—É—á–∏—Ç–µ —Ñ—Ä–µ–π–º —Å –æ—Ç—Å–æ—Ä—Ç–∏—Ä–æ–≤–∞–Ω–Ω—ã–º–∏ –ø–æ –∏–º–µ–Ω–∞–º –∫–æ–ª–æ–Ω–∫–∞–º (f e d c b a)
# NOTE - —Å–æ—Ä—Ç–∏—Ä–æ–≤–∫–∞ –¥–æ–ª–∂–Ω–∞ –±—ã—Ç—å –∞–≤—Ç–æ–º–∞—Ç–∏—á–µ—Å–∫–æ–π

   f  e  d  c  b  a
0  6  9  4  7  5  2
1  6  1  3  8  5  6
2  3  8  8  1  7  0
3  0  2  0  5  3  4
4  9  9  0  8  2  9

–û—Ç–æ–±—Ä–∞–∑–∏—Ç–µ –∫–∞–∂–¥—É—é 20—é –∑–∞–ø–∏—Å—å –≤–æ —Ñ—Ä–µ–π–º–µ –∏ —Ç–æ–ª—å–∫–æ –∫–æ–ª–æ–Ω–∫–∏ `Manufacturer`, `Model`, `Type`:

In [15]:
df = pd.read_csv('https://raw.githubusercontent.com/AleksDevEdu/ml_edu/master/datasets/Cars93_miss.csv')

df.iloc[::20][['Manufacturer', 'Model', 'Type']]

# TODO - –æ—Ç–æ–±—Ä–∞–∑–∏—Ç–µ –∑–∞–ø–∏—Å—å —Å –ø–µ—Ä–∏–æ–¥–∏—á–Ω–æ—Å—Ç—å—é –≤–æ —Ñ—Ä–µ–π–º–µ –∏ –æ–ø—Ä–µ–¥–µ–ª–µ–Ω–Ω—ã–µ –∫–æ–ª–æ–Ω–∫–∏

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

–ü–æ–ª—É—á–∏—Ç–µ —Ä—è–¥, –∫–æ—Ç–æ—Ä—ã–π —Å–æ–¥–µ—Ä–∂–∏—Ç –¥–ª–∏–Ω—ã —Å—Ç—Ä–æ–∫:

In [16]:
ds = pd.Series(['how', 'to', 'use', 'pandas?'])
l=[]
for i in list(ds):
  l.append(len(i))
df = pd.Series(l)
df
# TODO - —Å–æ–∑–¥–∞–π—Ç–µ —Ä—è–¥, —Å–æ–¥–µ—Ä–∂–∞—â–∏–π –¥–ª–∏–Ω—ã —Å—Ç—Ä–æ–∫:
# 0    3
# 1    2
# 2    3
# 3    7
# dtype: int64

0    3
1    2
2    3
3    7
dtype: int64